const status = {
  progress: 'Work in progress',
  ready: 'Ready',
  downloaded: 'Downloaded',
};

export const data = [
  {
    id: 1,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.progress,
    statusId: 'progress',
  },
  {
    id: 2,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.progress,
    statusId: 'progress',
  },
  {
    id: 3,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.ready,
    statusId: 'ready',
  },
  {
    id: 4,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.ready,
    statusId: 'ready',
  },
  {
    id: 5,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.progress,
    statusId: 'progress',
  },
  {
    id: 6,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.progress,
    statusId: 'progress',
  },
  {
    id: 7,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.downloaded,
    statusId: 'downloaded',
  },
  {
    id: 8,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.downloaded,
    statusId: 'downloaded',
  },
  {
    id: 9,
    photos: ['img/photo_1.png', 'img/photo_2.png', 'img/photo_3.png'],
    number: 1160,
    shape: 'Rectangle',
    name: 'John Ivanov',
    address: '45 Grand Central Terminal, New York',
    date: '4/18/2018',
    total: 250,
    status: status.downloaded,
    statusId: 'downloaded',
  },
];
